fuzzing_engines:
- libfuzzer
homepage: https://commons.apache.org/proper/commons-collections/
language: jvm
main_repo: http://gitbox.apache.org/repos/asf/commons-collections.git
sanitizers:
- address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"